import * as XLSX from "xlsx";

// ======================================================
// 📄 PDF EXPORT — Uses html2pdf.js for full Unicode
//    (Amharic, Arabic, etc.) support via browser rendering
// ======================================================
export const exportCustomersPDF = async ({
  customers = [],
  totalCustomers,
  creditCustomers,
  totalOutstanding,
  filename = "customers_report",
}) => {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Build the HTML to render into PDF
  const html = `
    <html>
    <head>
      <meta charset="UTF-8" />
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: 'Segoe UI', Arial, sans-serif;
          font-size: 12px;
          color: #1a1a2e;
          padding: 24px;
          background: #fff;
        }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          margin-bottom: 20px;
          padding-bottom: 14px;
          border-bottom: 3px solid #6366f1;
        }
        .company-name {
          font-size: 22px;
          font-weight: 800;
          color: #6366f1;
          letter-spacing: 1px;
        }
        .company-sub {
          font-size: 11px;
          color: #666;
          margin-top: 4px;
        }
        .report-meta {
          text-align: right;
          font-size: 11px;
          color: #555;
        }
        .report-meta .date {
          font-weight: 600;
          font-size: 12px;
          color: #333;
        }
        .summary-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 12px;
          margin-bottom: 20px;
        }
        .summary-card {
          background: #f5f5ff;
          border: 1px solid #e0e0ff;
          border-radius: 8px;
          padding: 12px 16px;
        }
        .summary-card .label {
          font-size: 10px;
          color: #888;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 4px;
        }
        .summary-card .value {
          font-size: 20px;
          font-weight: 700;
          color: #333;
        }
        .summary-card .value.danger { color: #ef4444; }
        table {
          width: 100%;
          border-collapse: collapse;
          font-size: 11px;
        }
        thead tr {
          background-color: #6366f1;
          color: #fff;
        }
        thead th {
          padding: 8px 10px;
          text-align: left;
          font-weight: 600;
          font-size: 10px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        tbody tr:nth-child(even) { background: #f8f8ff; }
        tbody tr:hover { background: #eef2ff; }
        td {
          padding: 8px 10px;
          border-bottom: 1px solid #e5e7eb;
          vertical-align: top;
        }
        .badge-paid {
          background: #dcfce7;
          color: #16a34a;
          padding: 2px 6px;
          border-radius: 4px;
          font-weight: 600;
          font-size: 10px;
        }
        .badge-credit {
          background: #fee2e2;
          color: #dc2626;
          padding: 2px 6px;
          border-radius: 4px;
          font-weight: 600;
          font-size: 10px;
        }
        .badge-active {
          background: #dcfce7;
          color: #15803d;
          padding: 2px 6px;
          border-radius: 4px;
          font-weight: 600;
          font-size: 10px;
        }
        .badge-inactive {
          background: #f3f4f6;
          color: #6b7280;
          padding: 2px 6px;
          border-radius: 4px;
          font-weight: 600;
          font-size: 10px;
        }
        .footer {
          margin-top: 20px;
          padding-top: 10px;
          border-top: 1px solid #e5e7eb;
          font-size: 10px;
          color: #aaa;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="company-name">DENSO TRACKER</div>
          <div class="company-sub">Customer Management Report</div>
        </div>
        <div class="report-meta">
          <div class="date">${dateStr}</div>
          <div>Generated by Denso Tracker System</div>
        </div>
      </div>

      <div class="summary-grid">
        <div class="summary-card">
          <div class="label">Total Customers</div>
          <div class="value">${totalCustomers}</div>
        </div>
        <div class="summary-card">
          <div class="label">Customers with Debt</div>
          <div class="value danger">${creditCustomers}</div>
        </div>
        <div class="summary-card">
          <div class="label">Total Outstanding Balance</div>
          <div class="value danger">${Number(totalOutstanding).toFixed(2)} Birr</div>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Customer Name</th>
            <th>Phone</th>
            <th>Company</th>
            <th>Balance (Birr)</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${customers.map((c, i) => `
            <tr>
              <td>${i + 1}</td>
              <td><strong>${c.name || ""}</strong></td>
              <td>${c.phone || ""}</td>
              <td>${c.company || "-"}</td>
              <td>
                <span class="${c.balance > 0 ? "badge-credit" : "badge-paid"}">
                  ${Number(c.balance || 0).toFixed(2)}
                </span>
              </td>
              <td>
                <span class="${c.status === "Active" ? "badge-active" : "badge-inactive"}">
                  ${c.status || "Active"}
                </span>
              </td>
            </tr>
          `).join("")}
        </tbody>
      </table>

      <div class="footer">
        Denso Tracker &bull; Confidential &bull; ${dateStr}
      </div>
    </body>
    </html>
  `;

  // Dynamically import html2pdf.js (avoids SSR issues and bundler errors)
  const html2pdf = (await import("html2pdf.js")).default;

  const container = document.createElement("div");
  container.innerHTML = html;
  document.body.appendChild(container);

  await html2pdf()
    .set({
      margin: [0, 0, 0, 0],
      filename: `${filename}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, letterRendering: true },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      pagebreak: { mode: ["avoid-all", "css", "legacy"] },
    })
    .from(container)
    .save();

  document.body.removeChild(container);
};

// ======================================================
// 📄 LEDGER PDF EXPORT — for CustomerDetails page
// ======================================================
export const exportLedgerPDF = async ({
  customer,
  ledger = [],
  filename,
}) => {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const totalDebits = ledger.reduce((s, l) => s + l.debit, 0);
  const totalCredits = ledger.reduce((s, l) => s + l.credit, 0);

  const html = `
    <html>
    <head>
      <meta charset="UTF-8" />
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; color: #1a1a2e; padding: 24px; background: #fff; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; padding-bottom: 14px; border-bottom: 3px solid #6366f1; }
        .company-name { font-size: 22px; font-weight: 800; color: #6366f1; }
        .report-meta { text-align: right; font-size: 11px; color: #555; }
        .profile-section { background: #f5f5ff; border-radius: 8px; padding: 14px 16px; margin-bottom: 16px; display: flex; gap: 24px; }
        .profile-item { display: flex; flex-direction: column; gap: 2px; }
        .profile-item .lbl { font-size: 10px; color: #888; font-weight: 600; text-transform: uppercase; }
        .profile-item .val { font-weight: 700; font-size: 13px; color: #333; }
        .balance-danger { color: #dc2626; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        thead tr { background-color: #6366f1; color: #fff; }
        thead th { padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; }
        tbody tr:nth-child(even) { background: #f8f8ff; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; }
        .badge { padding: 2px 6px; border-radius: 4px; font-weight: 600; font-size: 10px; }
        .sale { background: #fee2e2; color: #dc2626; }
        .payment { background: #dcfce7; color: #16a34a; }
        .debit { color: #dc2626; font-weight: 600; }
        .credit { color: #16a34a; font-weight: 600; }
        .summary { margin-top: 16px; border-top: 2px solid #6366f1; padding-top: 10px; display: flex; gap: 24px; justify-content: flex-end; }
        .summary-item .lbl { font-size: 10px; color: #888; text-transform: uppercase; }
        .summary-item .val { font-weight: 700; font-size: 14px; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #aaa; text-align: center; }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="company-name">DENSO TRACKER</div>
          <div style="font-size:11px;color:#666;margin-top:4px">Customer Ledger Statement</div>
        </div>
        <div class="report-meta">
          <div style="font-weight:600;font-size:12px;color:#333">${dateStr}</div>
        </div>
      </div>

      <div class="profile-section">
        <div class="profile-item"><div class="lbl">Customer Name</div><div class="val">${customer.name || ""}</div></div>
        <div class="profile-item"><div class="lbl">Phone</div><div class="val">${customer.phone || ""}</div></div>
        ${customer.company ? `<div class="profile-item"><div class="lbl">Company</div><div class="val">${customer.company}</div></div>` : ""}
        <div class="profile-item"><div class="lbl">Current Balance</div><div class="val balance-danger">${Number(customer.balance || 0).toFixed(2)} Birr</div></div>
      </div>

      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Description</th>
            <th>Debit (Sale)</th>
            <th>Credit (Payment)</th>
            <th>Balance</th>
          </tr>
        </thead>
        <tbody>
          ${ledger.map(l => `
            <tr>
              <td>${new Date(l.date).toLocaleDateString()}</td>
              <td><span class="badge ${l.type === "SALE" ? "sale" : "payment"}">${l.type}</span></td>
              <td>${l.description || ""}</td>
              <td class="debit">${l.debit > 0 ? Number(l.debit).toFixed(2) : "-"}</td>
              <td class="credit">${l.credit > 0 ? Number(l.credit).toFixed(2) : "-"}</td>
              <td style="font-weight:600">${Number(l.balance).toFixed(2)}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>

      <div class="summary">
        <div class="summary-item"><div class="lbl">Total Debits</div><div class="val debit">${totalDebits.toFixed(2)} Birr</div></div>
        <div class="summary-item"><div class="lbl">Total Credits</div><div class="val credit">${totalCredits.toFixed(2)} Birr</div></div>
        <div class="summary-item"><div class="lbl">Closing Balance</div><div class="val balance-danger">${Number(customer.balance || 0).toFixed(2)} Birr</div></div>
      </div>

      <div class="footer">Denso Tracker &bull; Confidential &bull; ${dateStr}</div>
    </body>
    </html>
  `;

  const html2pdf = (await import("html2pdf.js")).default;
  const container = document.createElement("div");
  container.innerHTML = html;
  document.body.appendChild(container);

  await html2pdf()
    .set({
      margin: [0, 0, 0, 0],
      filename: `${filename || "ledger"}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, letterRendering: true },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    })
    .from(container)
    .save();

  document.body.removeChild(container);
};

// ======================================================
// 📊 EXCEL EXPORT — unchanged, works with Unicode natively
// ======================================================
export const exportToExcel = (data, filename) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");
  XLSX.writeFile(workbook, `${filename}.xlsx`);
};

// Keep old exportToPDF as a thin shim for any other callers
export const exportToPDF = (title, columns, data, filename) => {
  console.warn("exportToPDF is deprecated. Use exportCustomersPDF or exportLedgerPDF instead.");
};
